Remove -U__STRICT_ANSI__ from CXXFLAGS
This caused compilation failures when build with clang on linux
Complaining with messages like:
  error: use of undeclared identifier '__float128'