Remove -U__STRICT_ANSI__ from CXXFLAGS
This caused compilation failures when build with clang like:
  error: use of undeclared identifier '__float128'